version: '3.12'

services:
  database:
    image: mariadb
    container_name: la_kantina_db
    environment:
      MARIADB_DATABASE: la_kantina
      MARIADB_ROOT_PASSWORD: mata
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db_scripts/tables.sql:/docker-entrypoint-initdb.d/1.sql
      # - ./db_scripts/users.sql:/docker-entrypoint-initdb.d/2.sql
      # - ./db_scripts/timecards.sql:/docker-entrypoint-initdb.d/3.sql
  api:
    depends_on:
    - database
    container_name: la_kantina_api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
      - DATABASE_HOST=database
    env_file:
      - .env
    restart: always